name: Test build Electron App

on:
  push:
    tags:
      - v/test/*

jobs:
  test-build:
    name: test build electron app

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.3
        with:
          node-version: 14

      - name: npm install
        run: |
          npm install

      - name: test build win app
        run: |
          npm run electron:publish-win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
